authe/urls.py
from django.urls import path
from authe import views
app_name='authe'

urlpatterns=[
    path('register/', views.register, name="register"),
    path('login/', views.login1, name="login"),
    path('logout/', views.logout1, name="logout"),
    ]

chat/urls.py
from django.urls import path
from chat import views
app_name='chat'
urlpatterns=[
    path('chatview/',views.chatview,name='chatview')
]

discuss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from discuss import views
urlpatterns = [
    path('admin/',admin.site.urls),
    path('w/',views.welcome,name="welcome"),
    path('i/',views.index,name="i"),
    path('a/',include('authe.urls')),
    path('',include('chat.urls')),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

authe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class registermodel(User):
    phone=models.BigIntegerField()
    age=models.IntegerField()
    gender=models.CharField(max_length=10, choices=[['Male','MALE'],['Female','FEMALE']])
    pic=models.ImageField(upload_to='profile/')
    dor=models.DateTimeField(default=timezone.now)
    

chat/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
from authe.models import registermodel
# Create your models here.
class chatmodel(models.Model):
    cid=models.ForeignKey(registermodel,on_delete=models.CASCADE)
    msg=models.CharField(max_length=500)
    datetime=models.DateTimeField(default=timezone.now)
    cimg=models.ImageField(upload_to='chatimg/', null=True)
    cfile=models.FileField(upload_to='chatdoc/',null=True)

chat/forms.py
from django.utils import timezone
from django import forms
from chat.models import chatmodel
class chatform(forms.Form):
    msg=forms.CharField(max_length=500,required=False)
    datetime=forms.SplitHiddenDateTimeWidget()
    cimg=forms.ImageField(required=False)
    cfile=forms.FileField(required=False)
    
    
    
    

authe/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from authe.models import registermodel
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def register(request):
    if request.method=='POST' and request.FILES:
        print('hai')
        print(request.POST)
        print(request.FILES)
        p=request.POST['password']
        pa=request.POST['repassword']
        if p==pa:
            registermodel.objects.create(username=request.POST['username'],
                                     first_name=request.POST['firstname'],
                                     last_name=request.POST['lastname'],
                                     email=request.POST['email'],
                                     phone=request.POST['phone'],
                                     password=make_password(request.POST['password']),
                                     age=request.POST['age'],
                                     gender=request.POST['gender'],
                                     pic=request.FILES['pic'])
        return HttpResponse('data is stored')

    return render(request,'register.html')

def login1(request):
    if request.method=='POST':
        print(request.POST)
        user=request.POST['username']
        pas=request.POST['password']
        user1=authenticate(username=user,password=pas)
        if user1:
            print(user1)
            login(request,user1)
            return redirect('/i')
    return render(request,'login.html')

def logout1(request):
    logout(request)
    return redirect('/w')

chat/views.py
from django.shortcuts import redirect, render
from chat.forms import chatform
from chat.models import chatmodel
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='/a/login/')
def chatview(request):
    form=chatform()
    res=chatmodel.objects.all()
    if request.method=='POST':
        form=chatform(request.POST,request.FILES)
        if form.is_valid():
            chatmodel.objects.create(cid_id=request.user.id,
                                     msg=form.cleaned_data['msg'],
                                     cimg=form.cleaned_data['cimg'],
                                     cfile=form.cleaned_data['cfile'])
            return render(request,'chat.html',{'form':form,'res':res})
    return render(request,'chat.html',{'form':form,'res':res})

discuss/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.decorators import login_required

def welcome(request):
    return render(request,'base.html')

@login_required(login_url='/login/')
def index(request):
    return render(request,'index.html')

authe/templates/partials/bootcss.html
{%load static %}
<link href="{%static 'boot/css/bootstrap-grid.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-grid.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-grid.rtl.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-grid.rtl.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-reboot.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-reboot.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-reboot.rtl.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-reboot.rtl.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-utilities.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-utilities.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-utilities.rtl.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap-utilities.rtl.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap.rtl.css' %}" rel="stylesheet" type="text/css">
<link href="{%static 'boot/css/bootstrap.rtl.min.css' %}" rel="stylesheet" type="text/css">

authe/templates/partials/bootjs.html
{%load static %}
<script src="{%static 'boot/js/bootstrap.bundle.js' %}" type="text/js"></script>
<script src="{%static 'boot/js/bootstrap.bundle.min.js' %}"  type="text/js"></script>
<script src="{%static 'boot/js/bootstrap.esm.js' %}"  type="text/js"></script>
<script src="{%static 'boot/js/bootstrap.esm.min.js' %}"  type="text/js"></script>
<script src="{%static 'boot/js/bootstrap.js' %}"  type="text/js"></script>
<script src="{%static 'boot/js/bootstrap.min.js' %}"  type="text/js"></script>

chat/templates/chat.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%block content%}
    <form method="POST" action="{% url 'chat:chatview'%}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="send">
    </form>
    {% if res %}
    <table border="2">
        <tr><td>cid</td><td>msg</td><td>cimg</td><td>cfile</td> </tr>
        {% for i in res %}
        <tr><td>{{i.cid}}</td><td>{{i.msg}}</td>
            {% if i.cimg  or i.cfile %}
            <td><img src='{{i.cimg.url}}' height="50" width="50"></td>
            <td>{{i.cfile}}</td>
            {% endif %}
             </tr>
        {% endfor %}
    </table>
    {% endif %}

    {%endblock%}
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>welcome page</title>


    <!-- Bootstrap core CSS -->
    {% include 'partials/bootcss.html' %}
    <link href="{% static 'css/headers.css' %}" rel="stylesheet" type="text/css">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
  </head>
  <body>
    
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
</svg>

<main>
  <h1 class="visually-hidden">Headers examples</h1>
   <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
      </ul>

      <div class="col-md-3 text-end">
        <a href="{%url 'authe:login' %}"><button type="button" class="btn btn-outline-primary me-2">Login</button></a>
        <a href="{%url 'authe:register' %}"><button type="button" class="btn btn-primary">Sign-up</button></a>
      </div>
    </header>
  </div>  
</main>


  {% include 'partials/bootjs.html' %}

      
  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en" class="h-100">
  {%load static%}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cover</title>
    {% include 'partials/bootcss.html' %}
    <link href="{%static 'css/cover.css'%}" rel="stylesheet">
   
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  
  <header class="mb-auto">
    <div>
      {%if user.is_authenticated %}
      <h3 class="float-md-start mb-0">{{user}}</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="{% url 'i' %}">Home</a>
        <a class="nav-link" href="{% url 'chat:chatview' %}">Chat</a>
        <a class="nav-link" href="#">Contact</a>
        <a class="nav-link" href="{% url 'authe:logout' %}">logout</a>
        {% endif %}
      </nav>
    </div>
  </header>
 {%block content%}
  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>
  {%endblock%}

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>

{%include 'partials/bootjs.html'%}
    
  </body>
</html>